version: '3'
# https://github.com/frappe/frappe_docker/blob/develop/devcontainer-example/docker-compose.yml
services:

  frappe-bench:
    container_name: frappe-bench
    image: frappe/bench:latest
    command: sleep infinity
    volumes:
      - ./:/workspace
      - ../uppsala:/workspace/uppsala
      - ../hfmts-data:/workspace/hfmts-data

    working_dir: /workspace
    # ports:
      # - "8000:8000"
      # - "8443:8443"

  redis-cache:
    container_name: redis-cache
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-cache-vol:/data

  redis-queue:
    container_name: redis-queue
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-queue-vol:/data

  redis-socketio:
    container_name: redis-socketio
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-socketio-vol:/data    

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"

  # postgresql:
  #   container_name: postgresql
  #   image: postgres:11.8
  #   restart: on-failure
  #   ports:
  #     - "127.0.0.1:5432:5432"
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - postgresql-vol:/var/lib/postgresql/data

  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=IeGoup2I
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb/frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - mariadb-vol:/var/lib/mysql


volumes:
  mariadb-vol:
  redis-cache-vol:
  redis-queue-vol:
  redis-socketio-vol: